// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PennyWise.Infrastructure.Data;

#nullable disable

namespace PennyWise.Infrastructure.Migrations
{
    [DbContext(typeof(PennyWiseDbContext))]
    [Migration("20260604000001_AddUserRole")]
    partial class AddUserRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PennyWise.Domain.Entities.Budget", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<decimal>("LimitAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.Property<int>("Month").HasColumnType("integer");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<int>("Year").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Budgets");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.Holding", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<decimal>("CurrentPrice").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                b.Property<string>("InstrumentName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<int>("InstrumentType").HasColumnType("integer");
                b.Property<Guid>("PortfolioId").HasColumnType("uuid");
                b.Property<DateTime>("PurchaseDate").HasColumnType("timestamp with time zone");
                b.Property<decimal>("PurchasePrice").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                b.Property<decimal>("Quantity").HasPrecision(18, 6).HasColumnType("numeric(18,6)");
                b.Property<string>("TickerSymbol").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("PortfolioId");
                b.ToTable("Holdings");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.Portfolio", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Portfolios");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.Transaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<DateTime>("TransactionDate").HasColumnType("timestamp with time zone");
                b.Property<int>("Type").HasColumnType("integer");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Transactions");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasDefaultValue("User");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.Budget", b =>
            {
                b.HasOne("PennyWise.Domain.Entities.User", "User")
                    .WithMany("Budgets").HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.Holding", b =>
            {
                b.HasOne("PennyWise.Domain.Entities.Portfolio", "Portfolio")
                    .WithMany("Holdings").HasForeignKey("PortfolioId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Portfolio");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.Portfolio", b =>
            {
                b.HasOne("PennyWise.Domain.Entities.User", "User")
                    .WithMany("Portfolios").HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.Transaction", b =>
            {
                b.HasOne("PennyWise.Domain.Entities.User", "User")
                    .WithMany("Transactions").HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.Portfolio", b =>
            {
                b.Navigation("Holdings");
            });

            modelBuilder.Entity("PennyWise.Domain.Entities.User", b =>
            {
                b.Navigation("Budgets");
                b.Navigation("Portfolios");
                b.Navigation("Transactions");
            });
#pragma warning restore 612, 618
        }
    }
}
